name: Download Charts data from backend and publish with GitHub Pages

on:
  workflow_dispatch:

jobs:
  download:
    name: Download data from servers
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    # Get master branch to get executable
    - uses: actions/checkout@v3
      with:
        ref: master

    # Get GitHub current data
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: newData

    # Used to transform JS (original data format) into JSON
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 14.x

    - name: Prepare destination environment
      run: |
        rm -Rf newData/.git newData/Charts

    - name: Download Charts data and transform to JSON
      run: |
        mkdir -p newData/Charts cache

        # Install node dependencies (fetch)
        pushd charts
            npm install
        popd

        # Do the job until finished correctly
        MAX=5
        WAIT=60
        while ! node charts/index.js cache newData/Charts
        do
            echo "[WARNING] Some files were not downloaded."

            if (( DONE++ >= MAX ))
            then
                echo "[ERROR] Max reties ${DONE}/${MAX} reached. Exiting." >&2
                exit 1
            fi

            echo "[WARNING] Retrying ${DONE}/${MAX} in ${WAIT} seconds..."
            sleep ${WAIT}
        done

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: newData
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
