name: Download maps and charts from backend and publish with GitHub Pages

# Schedule each day at 8:30am UTC (10:30 CEST, after data is published by authorities)
on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  download:
    name: Download data from servers
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    # Get master branch to get executable
    - uses: actions/checkout@v4
      with:
        ref: 'master'

    # Used to transform JS (original data format) into JSON
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 14.x

    - name: Prepare destination environment
      run: |
        mkdir -p newData

        # Minimum info for repo and for web
        cp README.md newData/
        cp README.md newData/index.html

    - name: Download Maps data and transform to SVG and JSON
      run: |
        mkdir -p newData/Maps
        pushd ./newData/Maps
            ../../bin/download-map-data.sh
        popd

    - name: Download Charts data and transform to JSON
      run: |
        mkdir -p newData/Charts cache

        # Install node dependencies (fetch)
        pushd charts
            npm install
        popd

        # Do the job until finished correctly
        MAX=5
        WAIT=60
        while ! node charts/index.js cache newData/Charts
        do
            echo "[WARNING] Some files were not downloaded."

            if (( DONE++ >= MAX ))
            then
                echo "[ERROR] Max reties ${DONE}/${MAX} reached. Exiting." >&2
                exit 1
            fi

            echo "[WARNING] Retrying ${DONE}/${MAX} in ${WAIT} seconds..."
            sleep ${WAIT}
        done

    - name: Download Barcelona data and transform to JSON
      run: |
        mkdir -p newData/Bcn cache

        # Install node dependencies (fetch)
        pushd bcn
            npm install
        popd

        # Do the job
        node bcn/index.js cache newData/Bcn

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: newData
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
