name: Download Maps data from backend and publish with GitHub Pages

on:
  workflow_dispatch:

jobs:
  download:
    name: Download data from servers
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    # Get master branch to get executable
    - uses: actions/checkout@v2
      with:
        ref: master

    # Get GitHub current data
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: newData

    # Used to transform JS (original data format) into JSON
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14.x

    - name: Prepare destination environment
      run: |
        rm -Rf newData/.git newData/Maps

    - name: Download Maps data and transform to SVG and JSON
      run: |
        mkdir -p newData/Maps
        pushd ./newData/Maps
            ../../bin/download-map-data.sh
        popd

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: newData
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
